# Generated by Django 6.0.7 on 2026-07-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('total_floors', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20)),
                ('floor', models.CharField(default='Floor 1', max_length=20)),
                ('slot_type', models.CharField(choices=[('STANDARD', 'Standard Vehicle'), ('COMPACT', 'Compact Car'), ('SUV', 'Large SUV / Truck'), ('EV', 'Electric Vehicle (EV) Charging'), ('ACCESSIBLE', 'Handicapped Accessible'), ('VIP', 'VIP Reserved')], default='STANDARD', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_covered', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglocation')),
            ],
            options={
                'ordering': ['floor', 'slot_number'],
                'unique_together': {('location', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('driver_name', models.CharField(max_length=120)),
                ('driver_phone', models.CharField(max_length=20)),
                ('driver_email', models.EmailField(blank=True, default='', max_length=254)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(default='Sedan', max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('qr_token', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingslot')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Digital Wallet / Card', max_length=50)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parking.booking')),
            ],
        ),
    ]
